Import Libraries

In [4]:
import pandas as pd
import seaborn as sns

Create Dataframe

In [ ]:
df = pd.read_csv(r"C:\Users\matheus.melo\Exploratory Data Analysis\.venv\Lib\TwoCenturiesOfUmRaces\TWO_CENTURIES_OF_UM_RACES.csv", low_memory=False)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,06.01.2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4

See the data that's been imported

In [10]:
df.head(10)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,06.01.2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4
5,2018,06.01.2018,Selva Costera (CHI),50km,22,6:25:01 h,NaN,ARG,1974.0,M,M40,7.792,5
6,2018,06.01.2018,Selva Costera (CHI),50km,22,6:28:00 h,Los Patagones,ARG,1979.0,F,W35,7.732,6
7,2018,06.01.2018,Selva Costera (CHI),50km,22,6:32:24 h,Reaktiva Chile,CHI,1967.0,F,W50,7.645,7
8,2018,06.01.2018,Selva Costera (CHI),50km,22,6:39:08 h,Puro Trail Osorno,CHI,1985.0,M,M23,7.516,8
9,2018,06.01.2018,Selva Costera (CHI),50km,22,6:45:11 h,Marlene Flores Team,CHI,1976.0,M,M40,7.404,9

Clean up data (Only want 100km or 100mi from 2018)

In [18]:
df[(df['Event distance/length'].isin(["100mi", '100km'])) & (df['Year of event']==2018)]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
1036,2018,24.-25.03.2018,Extreme North Dakota Sandhills Ultra Run Exper...,100mi,3,30:27:00 h,NaN,USA,1991.0,M,M23,5.285,1034
1037,2018,24.-25.03.2018,Extreme North Dakota Sandhills Ultra Run Exper...,100mi,3,46:24:00 h,NaN,USA,1970.0,F,W45,3.468,1035
1038,2018,24.-25.03.2018,Extreme North Dakota Sandhills Ultra Run Exper...,100mi,3,46:24:00 h,NaN,USA,1980.0,M,M35,3.468,1036
1039,2018,24.-25.03.2018,Extreme North Dakota Sandhills Ultra Run Exper...,100km,3,17:20:00 h,NaN,USA,1979.0,M,M35,5.769,1037
1040,2018,24.-25.03.2018,Extreme North Dakota Sandhills Ultra Run Exper...,100km,3,18:29:00 h,NaN,CAN,1983.0,M,M23,5.41,1038
...,...,...,...,...,...,...,...,...,...,...,...,...,...
661449,2018,27.-28.10.2018,Cactus Rose 100 Mile (USA),100mi,17,33:03:50 h,NaN,USA,1955.0,M,M60,4.867,35525
661450,2018,27.-28.10.2018,Cactus Rose 100 Mile (USA),100mi,17,33:31:42 h,NaN,USA,1987.0,M,M23,4.8,35548
661451,2018,27.-28.10.2018,Cactus Rose 100 Mile (USA),100mi,17,34:09:28 h,NaN,USA,1974.0,F,W40,4.712,303539
661452,2018,27.-28.10.2018,Cactus Rose 100 Mile (USA),100mi,17,34:16:34 h,NaN,USA,1974.0,M,M40,4.695,55267
661453,2018,27.-28.10.2018,Cactus Rose 100 Mile (USA),100mi,17,34:41:23 h,NaN,USA,1960.0,F,W55,4.639,35528

Filter for only USA races

In [ ]:
df[df['Event name'].str.split('(').str.get(1).str.split(')').str.get(0) == 'CAN']

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,06.01.2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7104223,2015,16.-17.10.2015,Endurance Challenge Chile 160km (CHI),160km,24,36:43:22 h,NaN,VEN,1981.0,M,M23,4.357,287590
7104224,2015,16.-17.10.2015,Endurance Challenge Chile 160km (CHI),160km,24,36:49:03 h,NaN,PER,1971.0,M,M40,4.346,18635
7104225,2015,16.-17.10.2015,Endurance Challenge Chile 160km (CHI),160km,24,36:49:56 h,NaN,CHI,1975.0,M,M35,4.344,167433
7104226,2015,16.-17.10.2015,Endurance Challenge Chile 160km (CHI),160km,24,36:54:25 h,NaN,CHI,1975.0,M,M35,4.335,422181
7104227,2015,16.-17.10.2015,Endurance Challenge Chile 160km (CHI),160km,24,37:16:37 h,NaN,CHI,1975.0,M,M35,4.292,167419

Combine Filters Together

In [29]:
df[(df['Event distance/length'].isin(["100mi", '100km'])) &
    (df['Year of event']==2018) &
    (df['Event name'].str.split('(').str.get(1).str.split(')').str.get(0) == 'USA')]

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
1362,2018,23.-24.03.2018,Antelope Island Buffalo Run 100 Mile (USA),100mi,48,15:58:20 h,"*North Logan, UT",USA,1971.0,M,M45,10.076,1360
1363,2018,23.-24.03.2018,Antelope Island Buffalo Run 100 Mile (USA),100mi,48,17:27:23 h,"*Cottonwood Heights, UT",USA,1976.0,M,M40,9.219,1361
1364,2018,23.-24.03.2018,Antelope Island Buffalo Run 100 Mile (USA),100mi,48,18:25:18 h,"*Farmington, UT",USA,1970.0,M,M45,8.736,1362
1365,2018,23.-24.03.2018,Antelope Island Buffalo Run 100 Mile (USA),100mi,48,19:03:23 h,"*Fort Collins, CO",USA,1978.0,M,M35,8.445,1363
1366,2018,23.-24.03.2018,Antelope Island Buffalo Run 100 Mile (USA),100mi,48,19:36:34 h,"*Taylorsville, UT",USA,1979.0,M,M35,8.207,1364
...,...,...,...,...,...,...,...,...,...,...,...,...,...
661449,2018,27.-28.10.2018,Cactus Rose 100 Mile (USA),100mi,17,33:03:50 h,NaN,USA,1955.0,M,M60,4.867,35525
661450,2018,27.-28.10.2018,Cactus Rose 100 Mile (USA),100mi,17,33:31:42 h,NaN,USA,1987.0,M,M23,4.8,35548
661451,2018,27.-28.10.2018,Cactus Rose 100 Mile (USA),100mi,17,34:09:28 h,NaN,USA,1974.0,F,W40,4.712,303539
661452,2018,27.-28.10.2018,Cactus Rose 100 Mile (USA),100mi,17,34:16:34 h,NaN,USA,1974.0,M,M40,4.695,55267
661453,2018,27.-28.10.2018,Cactus Rose 100 Mile (USA),100mi,17,34:41:23 h,NaN,USA,1960.0,F,W55,4.639,35528

Turn the filters into a new dataframe

In [30]:
filtered_df = df[(df['Event distance/length'].isin(["100mi", '100km'])) &
             (df['Year of event']==2018) &
             (df['Event name'].str.split('(').str.get(1).str.split(')').str.get(0) == 'USA')]